language: scala
scala:
   - 2.13.1
   - 2.12.10
jdk:
  - oraclejdk11
script:
  - sbt "project core" compile test scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
cache:
  directories:
    - $HOME/.ivy2/cache
