# See https://github.com/novus/salat/blob/master/.travis.yml
language: scala
scala:
   - 2.11.11
   - 2.12.4
jdk:
  - oraclejdk8

script:
  - sbt clean test
  - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
